
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

import tkinter as tk
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from administracion_modificar_descuento import AdministracionModificarDescuento
from administracion_modificar_usuario import AdministracionModificarUsuario
from administracion_ver_reserva_particular import AdministracionVerReservaParticular
from administracion_ver_reservas import AdministracionVerReservas
from administracion_carga_sala import AdministracionCargaSala
from administracion_modificar_sala import AdministracionModificarSala
from administracion_eliminar_sala import AdministracionEliminarSala


class Administracion(tk.Toplevel):
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./assets/administracion")

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def __init__(self, master=None):

        super().__init__(master)
        self.master = master
        self.configure(bg="#FFFFFF")
        self.geometry("559x457")
        # Icono del programa
        self.iconbitmap(r'assets\cinemark.ico')
        # Titulo del programa
        self.title("Cinemark")
        self.create_widgets()

    def open_administracion_reserva_particular(self):
        AdministracionVerReservaParticular(self.master)

    def open_administracion_modificar_sala(self):
            AdministracionModificarSala(self.master)

    def open_administracion_carga_sala(self):
        AdministracionCargaSala(self.master)

    def open_administracion_eliminar_sala(self):
        AdministracionEliminarSala(self.master)

    def open_administracion_modificar_descuento(self):
        AdministracionModificarDescuento(self.master)

    def open_administracion_ver_reservas(self):
        AdministracionVerReservas(self.master)

    def open_administracion_modificar_usuario(self):
        AdministracionModificarUsuario(self.master)

    def create_widgets(self):
        canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=457,
            width=559,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        canvas.create_text(
            210.0,
            7.0,
            anchor="nw",
            text="Cinemark",
            fill="#11AC0E",
            font=("Inter Bold", 20 * -1)
        )

        canvas.create_text(
            62.0,
            37.0,
            anchor="nw",
            text="Bienvenido a la ventana de Administracion ",
            fill="#000000",
            font=("Inter Bold", 20 * -1)
        )

        button_image_carga_sala = PhotoImage(
            file= self.relative_to_assets("button_cargar_sala.png"))
        button_carga_sala = Button(
            self,
            image = button_image_carga_sala,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_carga_sala(),
            relief="flat"
        )
        button_carga_sala.place(
            x=23.0,
            y=145.0,
            width=123.0,
            height=61.0
        )

        button_image_ver_reservas = PhotoImage(
            file= self.relative_to_assets("button_ver_reservas.png"))
        button_ver_reservas = Button(
            self, 
            image = button_image_ver_reservas,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_ver_reservas(),
            relief="flat"
        )
        button_ver_reservas.place(
            x=109.0,
            y=350.0,
            width=123.0,
            height=88.0
        )

        button_image_modificar_sala = PhotoImage(
            file= self.relative_to_assets("button_modificar_sala.png"))
        button_modificar_sala = Button(
            self, 
            image = button_image_modificar_sala,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_modificar_sala(),
            relief="flat"
        )
        button_modificar_sala.place(
            x=100.0,
            y=230.0,
            width=123.0,
            height=88.0
        )

        button_image_eliminar_sala = PhotoImage(
            file= self.relative_to_assets("button_eliminar_sala.png"))
        button_eliminar_sala = Button(
            self, 
            image = button_image_eliminar_sala,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_eliminar_sala(),
            relief="flat"
        )
        button_eliminar_sala.place(
            x=300.0,
            y=230.0,
            width=123.0,
            height=88.0
        )

        button_image_modificar_descuento = PhotoImage(
            file= self.relative_to_assets("button_modificar_descuento.png"))
        button_modificar_descuento = Button(
            self, 
            image = button_image_modificar_descuento,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_modificar_descuento(),
            relief="flat"
        )
        button_modificar_descuento.place(
            x=182.0,
            y=145.0,
            width=123.0,
            height=61.0
        )

        button_image_reserva_particular = PhotoImage(
            file= self.relative_to_assets("button_reserva_particular.png"))
        button_reserva_particular = Button(
            self,
            image = button_image_reserva_particular,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_reserva_particular(),
            relief="flat"
        )
        button_reserva_particular.place(
            x=358.0,
            y=145.0,
            width=123.0,
            height=61.0
        )

        button_image_modificar_usuario = PhotoImage(
            file = self.relative_to_assets("button_modificar_usuario.png"))
        button_modificar_usuario = Button(
            self, 
            image = button_image_modificar_usuario,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.open_administracion_modificar_usuario(),
            relief="flat"
        )
        button_modificar_usuario.place(
            x=293.0,
            y=380.0,
            width=123.0,
            height=61.0
        )

        canvas.create_text(
            34.0,
            76.0,
            anchor="nw",
            text="------------------   Funcionalidades    --------------------",
            fill="#000000",
            font=("Inter Bold", 20 * -1)
        )

        self.resizable(False, False)
        self.mainloop()

    def open(self):
        pass


if __name__ == "__main__":
    # app = Administracion(Tk())
    pass
