# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Entry, Text, Button, Frame, Canvas
from login import Login
from BDD.creando_bdd import create_connection
from BDD.creando_tablas_bdd import creando_tablas
from BDD.insertando_datos_bdd import insert_data


class Application(Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.master = master
        self.pack()
        self.create_widgets()

    def create_widgets(self):
        self.button = Button(self)
        self.button["text"] = "Abrir Cinemark"
        self.button["command"] = self.open_login
        self.button.pack()

    def open_login(self):
        Login(self.master)


if __name__ == "__main__":
    database = "Cinemark.db"
    # create_connection(database)
    # creando_tablas(database)
    # insert_data(database)
    root = Tk()
    root.geometry('250x100')
    root.title("Cinemark")
    root.iconbitmap(r'assets\cinemark.ico')
    app = Application(master=root)
    app.mainloop()
