
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Toplevel
from cliente_eliminar_reserva import ClienteEliminarReserva
from cliente_historico import ClienteHistorico
from cliente_reserva import ClienteReserva
from cliente_crear_reserva import ClienteCrearReserva
from cliente_eliminar_reserva import ClienteEliminarReserva


class Cliente(Toplevel):
    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path("./assets/cliente")

    def relative_to_assets(self, path: str) -> Path:
        return self.ASSETS_PATH / Path(path)

    def __init__(self, master=None, id_cliente=None):
        super().__init__(master)
        self.master = master
        self.id_cliente = id_cliente
        self.configure(bg="#FFFFFF")
        self.geometry("400x353")
        # Icono del programa
        self.iconbitmap(r'assets\cinemark.ico')
        # Titulo del programa
        self.title("Cinemark")
        self.create_widgets()

    def cliente_crear_reservas(self):
        ClienteCrearReserva(self.master, self.id_cliente)

    def cliente_eliminar_reservas(self):
        ClienteEliminarReserva(self.master, self.id_cliente)

    def cliente_reservas(self):
        ClienteReserva(self.master, self.id_cliente)

    def cliente_historico(self):
        ClienteHistorico(self.master, self.id_cliente)

    def create_widgets(self):

        canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=453,
            width=479,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        canvas.create_text(
            170.0,
            7.0,
            anchor="nw",
            text="Cinemark",
            fill="#11AC0E",
            font=("Inter Bold", 20 * -1)
        )

        canvas.create_text(
            72.0,
            37.0,
            anchor="nw",
            text="Bienvenido a la ventana de Cliente",
            fill="#000000",
            font=("Inter Bold", 20 * -1)
        )

        button_image_mis_reservas = PhotoImage(
            file = self.relative_to_assets("button_mis_reservas.png"))
        button_mis_reservas = Button(
            self,
            image = button_image_mis_reservas ,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.cliente_reservas(),
            relief="flat"
        )
        button_mis_reservas.place(
            x=178.0,
            y=128.0,
            width=123.0,
            height=61.0
        )

        button_image_crear_reserva = PhotoImage(
            file = self.relative_to_assets("button_crear_reserva.png"))
        button_crear_reserva = Button(
            self,
            image = button_image_crear_reserva ,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.cliente_crear_reservas(),
            relief="flat"
        )
        button_crear_reserva.place(
            x=20.0,
            y=128.0,
            width=123.0,
            height=61.0
        )

        button_image_eliminar_reserva = PhotoImage(
            file = self.relative_to_assets("button_eliminar_reserva.png"))
        button_eliminar_reserva = Button(
            self,
            image = button_image_eliminar_reserva ,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.cliente_eliminar_reservas(),
            relief="flat"
        )
        button_eliminar_reserva.place(
            x=20.0,
            y=250.0,
            width=123.0,
            height=61.0
        )

        button_image_historico_entradas = PhotoImage(
            file = self.relative_to_assets("button_historico_entradas.png"))
        button_historico_entradas = Button(
            self,
            image = button_image_historico_entradas,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: self.cliente_historico(),
            relief="flat"
        )
        button_historico_entradas.place(
            x=178.0,
            y=250.0,
            width=123.0,
            height=61.0
        )

        canvas.create_text(
            76.0,
            75.0,
            anchor="nw",
            text="----------    Acciones    ----------",
            fill="#000000",
            font=("Inter Bold", 20 * -1)
        )

        self.resizable(False, False)
        self.mainloop()


if __name__ == "__main__":
    app = Cliente(Tk())
    pass
